# site properties and page defaults
title: Control, Optimization, and Learning for Autonomy Lab
header: images/ut-campus.jpeg
footer: images/ut-campus.png

# site nav bar
nav:
  - link: team
  - link: research
  - link: publication
  - link: join


# base directory where site is hosted
logo: logo.png
header: images/ut-campus.jpeg
footer: images/ut-campus.png
baseurl: /

# site social media and other links
links:
  google-scholar: xxxxx
  twitter: xxxx

### advanced settings

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

# jekyll theme
theme: null


# Google Analytics
google_analytics: G-QF28DYFVNL
