# site properties and page defaults
title: Control, Optimization, and Online Learning for Autonomy Lab
logo: images/logo.png
header: images/ut-campus.jpeg
footer: images/ut-campus.jpeg

# site nav bar
nav:
  - link: team
  - link: research
  - name: "papers"
    href: "/publications"
  - link: join


# base directory where site is hosted
logo: images/logo.png
header: images/ut-campus.jpeg
footer: images/ut-campus.jpeg
baseurl: /

# site social media and other links
links:
  google-scholar: xxxxx

### advanced settings

# default front matter parameters for markdown files
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

# collections
collections:
  members:
    output: true

# sass settings
sass:
  sass_dir: css

# syntax highlighting
highlighter: rouge

# plugins
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-github-metadata
  # - jekyll-avatar
  # - jekyll-gist
  # - jekyll-mentions
  # - jekyll-relative-links
  # - jemoji

plugins: ['jekyll/scholar']
plugins_dir: [jekyll-scholar]

scholar:
  style: apa #american-institute-of-aeronautics-and-astronautics #modern-language-association  #chicago-author-date #, apa, chicago-author-date, ieee, , nature, vancouver
  locale: en

  sort_by: none
  order: ascending
  group_by: year
  group_order: descending
  bibliography_group_tag: h3
  bibliography_list_tag: ul
  bibliography_item_tag: ul #nobull

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib # "{{reference}}"

  replace_strings: true
  join_strings:    true

  details_dir:    bibliography
  details_layout: bibtex.html
  details_link:   Details

  query: "@*"

# jekyll theme
theme: null




