- id: doi:10.1016/j.ecolind.2020.107096
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
    - type: pdf
      link: https://greenelab.github.io/scihub-manuscript/
  tags:
    - monitoring
    

- id: doi:10.1111/faf.12525
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
    - type: pdf
      link: https://greenelab.github.io/scihub-manuscript/
    - type: source
      link: https://github.com/greenelab/scihub-manuscript
      text: Manuscript source
    - type: source
      link: https://github.com/greenelab/scihub
      text: Analyses source
  tags:
    - COVID-19
    - fisheries
    - seafood


- id: 10.1002/ecy.2546
  image: https://quantmarineecolab.github.io/images/journal_covers/2018_WhiteSmith_Ecology.png
  extra-links:
    - type: pdf
      link: pdfs/2018_WhiteSmith_Ecology.pdf
    - type: source
      link: https://github.com/eastonwhite/BodiePikaMetapop
      text: Code
  tags:
    - pikas
    - spatial ecology
    - conservation

      

- id: 10.1186/1745-6150-9-23
  image: https://quantmarineecolab.github.io/images/journal_covers/2015_White_etal_ConBio.png
  extra-links:
    - type: pdf
      link: pdfs/2015_White_etal_ConBio.pdf
    - type: source
      link: https://github.com/eastonwhite/Cocos_Models
      text: Code
  tags:
    - sharks and rays
    - marine protected areas
    - conservation



- id: 10.1186/1745-6150-9-23
  image: https://quantmarineecolab.github.io/images/journal_covers/2014_White_etal_BiologyDirect.png
  extra-links:
    - type: pdf
      link: pdfs/2014_White_etal_BiologyDirect.pdf
    - type: source
      link: https://github.com/eastonwhite/LemonShark_Models
      text: Code
  tags:
    - sharks and rays
    - population model
    - conservation


- id: 10.3354/meps10966
  image: https://quantmarineecolab.github.io/images/journal_covers/2014_Kessel_etal_MEPS.png
  extra-links:
    - type: pdf
      link: pdfs/2014_Kessel_etal_MEPS.pdf
  tags:
    - sharks and rays
    - seasonality




- id: 10.1016/j.marpol.2014.03.012
  image: https://quantmarineecolab.github.io/images/journal_covers/2014_Robinson_etal_MarinePol.png
  extra-links:
    - type: pdf
      link: pdfs/2014_Robinson_etal_MarinePol.pdf
  tags:
    - conservation
    - biodiversity




- id: 10.1111/1365-2664.12177
  image: https://quantmarineecolab.github.io/images/journal_covers/2014_GerberWhite_JAppEco.png
  extra-links:
    - type: pdf
      link: pdfs/2014_GerberWhite_JAppEco.pdf
  tags:
    - conservation
    - population model



- id: 10.1111/acv.12051
  image: https://quantmarineecolab.github.io/images/journal_covers/2014_Senko_et_al_AnimConserv.png
  extra-links:
    - type: pdf
      link: pdfs/2014_Senko_et_al_AnimConserv.pdf
  tags:
    - conservation
    - fisheries
      

