- id: doi:10.1016/j.ecolind.2020.107096
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
    - type: pdf
      link: https://greenelab.github.io/scihub-manuscript/
  tags:
    - monitoring
    

- id: doi:10.1111/faf.12525
  image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp
  extra-links:
    - type: preprint
      link: https://doi.org/10.7287/peerj.preprints.3100v1
    - type: pdf
      link: https://greenelab.github.io/scihub-manuscript/
    - type: source
      link: https://github.com/greenelab/scihub-manuscript
      text: Manuscript source
    - type: source
      link: https://github.com/greenelab/scihub
      text: Analyses source
  tags:
    - COVID-19
    - fisheries
    - seafood
      




- id: 10.1111/1365-2664.12177
  image: ![journal cover](images/journal_covers/2014_Senko_et_al_AnimConserv.png)
  extra-links:
    - type: pdf
      link: pdfs/2014_Senko_et_al_AnimConserv.pdf
    - type: source
      link: https://github.com/greenelab/scihub-manuscript
      text: Code
  tags:
    - conservation
    - fisheries




- id: 10.1111/acv.12051
  image: ![journal cover](images/journal_covers/2014_Senko_et_al_AnimConserv.png)
  extra-links:
    - type: pdf
      link: pdfs/2014_Senko_et_al_AnimConserv.pdf
    - type: source
      link: https://github.com/greenelab/scihub-manuscript
      text: Code
  tags:
    - conservation
    - fisheries
      

